name: Test & Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.414

      - name: Install Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Build and Test
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test --configuration Release --no-restore

      - name: Publish Console App
        if: success()
        run: |
          dotnet publish ./src/Marion.Dalifard.Ocr.Console/Marion.Dalifard.Ocr.Console.csproj -c Release -r win-x64 --self-contained true -o publish --no-restore /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name:  Publish win-x64 ocr
          path: ./win-x64/ocr.exe
