name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.414'

      - name: Install Leptonica and Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y libleptonica-dev tesseract-ocr libtesseract-dev

      - name: Verify Tesseract and Leptonica Installation
        run: |
          tesseract --version
          ldconfig -p | grep libleptonica

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/Marion.Dalifard.Ocr.Console/Marion.Dalifard.Ocr.Console.csproj -c Release -r win-x64 --self-contained true -o ./publish --no-restore /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: win-x64-ocr-exe
          path: ./publish/ocr.exe
